### 블록 확인
GET http://localhost:3000/blocks


### 3000번에서 두개 마이닝
POST http://localhost:3000/blocks
Content-Type: application/json


### 4000 과 3000 p2p 연결
POST http://localhost:3000/peers
Content-Type: application/json

{
    "peer": "ws://localhost:4000"
}

### 4000번 쪽 블록 확인 (총 3개)
GET http://localhost:4000/blocks

### 4000번에서 한개 마이닝
POST http://localhost:4000/blocks
Content-Type: application/json

### 3000번 쪽 블록 확인 (총 4개)
GET http://localhost:3000/blocks

### 나의 잔고 - 150원
GET http://localhost:3000/me/balance


### 다른 주소로 10원 보내보기
POST http://localhost:3000/transactions/
Content-Type: application/json

{
    "address": "04f20aac39b4c5f79355c053fdaf30410820400bb83ad93dd8ff16834b555e0f6262efba6ea94a87d3c267b5e6aca433ca89b342ac95c40230349ea4bf9caff1ed",
    "amount": 10
}

### 나의 잔고 - 150원
GET http://localhost:4000/me/balance

### 다른 주소로 60원 보내보기
POST http://localhost:3000/transactions/
Content-Type: application/json

{
    "address": "04f20aac39b4c5f79355c053fdaf30410820400bb83ad93dd8ff16834b555e0f6262efba6ea94a87d3c267b5e6aca433ca89b342ac95c40230349ea4bf9caff1ed",
    "amount": 60
}

### 멤풀 확인
GET http://localhost:3000/transactions/

### 4000번에서 한개 마이닝 및 멤풀 처리
POST http://localhost:4000/blocks
Content-Type: application/json

### 멤풀 확인
GET http://localhost:3000/transactions/

### 나의 잔고 - 80원 + 50원(마이닝)
GET http://localhost:3000/me/balance

### 다른 주소로 남은 돈 130원 보내보기
POST http://localhost:3000/transactions/
Content-Type: application/json

{
    "address": "04f20aac39b4c5f79355c053fdaf30410820400bb83ad93dd8ff16834b555e0f6262efba6ea94a87d3c267b5e6aca433ca89b342ac95c40230349ea4bf9caff1ed",
    "amount": 130
}

### 3000번에서 한개 마이닝 및 멤풀 처리
POST http://localhost:3000/blocks
Content-Type: application/json

### 나의 잔고 - 50원(마이닝)
GET http://localhost:3000/me/balance